name: Déployer le site Jekyll sur GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.161.0
        with:
          ruby-version: '3.1' # Non nécessaire si un fichier .ruby-version est présent
          bundler-cache: true # Exécute 'bundle install' et met en cache les gems installées automatiquement
          cache-version: 0 # Incrémentez ce numéro si vous avez besoin de re-télécharger les gems en cache

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm run build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
